name: digital_store_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  sqlite3: ^1.6.4
  envify: ^2.0.2
  uuid: ^3.0.6
  dart_jsonwebtoken: ^2.4.1
  redis: ^3.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  envify_generator: any
  build_runner: ^2.1.7
  
